services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    restart: unless-stopped
    environment:
      - CASSANDRA_CLUSTER_NAME=TheHive
    volumes:
      - cassandradata:/var/lib/cassandra
    networks:
      - SOC_NET

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    networks:
      - SOC_NET

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: ["server", "/data", "--console-address", ":9002"]
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - miniodata:/data
    networks:
      - SOC_NET

  cortex:
    image: thehiveproject/cortex:3.2.1
    container_name: cortex
    restart: unless-stopped
    depends_on:
      - elasticsearch
    environment:
      - job_directory=/tmp/cortex-jobs
      - docker_job_directory=/tmp/cortex-jobs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cortex/analyzers:/opt/Cortex-Analyzers/analyzers:ro
      - ./cortex/responders:/opt/Cortex-Analyzers/responders:ro
      - /tmp/cortex-jobs:/tmp/cortex-jobs
      - ./cortex/application.conf:/cortex/application.conf:ro
    ports:
      - "9001:9001"
    privileged: true
    networks:
      - SOC_NET

  thehive:
    image: strangebee/thehive:5.3
    container_name: thehive
    restart: unless-stopped
    depends_on:
      - cassandra
      - elasticsearch
      - minio
      - cortex
    environment:
      - JVM_OPTS=-Xms1024M -Xmx1024M
    command:
      - --secret
      - "lab123456789"
      - "--cql-hostnames"
      - "cassandra"
      - "--index-backend"
      - "elasticsearch"
      - "--es-hostnames"
      - "elasticsearch"
      - "--s3-endpoint"
      - "http://minio:9002"
      - "--s3-access-key"
      - "minioadmin"
      - "--s3-secret-key"
      - "minioadmin"
      - "--s3-use-path-access-style"
    volumes:
      - thehivedata:/var/lib/thehive
      - ./thehive/application.conf:/etc/thehive/application.conf:ro
    ports:
      - "9000:9000"
    networks:
      - SOC_NET

  misp:
    image: coolacid/misp-docker:core-v2.4.176a
    container_name: misp
    restart: unless-stopped
    depends_on:
      - misp_mysql
      - redis
    environment:
      - MYSQL_HOST=misp_mysql
      - MYSQL_DATABASE=mispdb
      - MYSQL_USER=mispuser
      - MYSQL_PASSWORD=misppass
      - MISP_ADMIN_EMAIL=mispadmin@lab.local
      - MISP_ADMIN_PASSPHRASE=mispadminpass
      - MISP_BASEURL=https://misp.local
      - TIMEZONE=Europe/London
      - INIT=true
      - CRON_USER_ID=1
      - REDIS_FQDN=redis
      - HOSTNAME=https://misp.local
    ports:
      - "80:80"
      - "443:443"
    networks:
      - SOC_NET

  misp_mysql:
    image: mysql:5.7
    container_name: misp_mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=mispdb
      - MYSQL_USER=mispuser
      - MYSQL_PASSWORD=misppass
      - MYSQL_ROOT_PASSWORD=mispass
    volumes:
      - mispsqldata:/var/lib/mysql
    networks:
      - SOC_NET

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    networks:
      - SOC_NET

volumes:
  cassandradata:
  elasticsearchdata:
  miniodata:
  cortexjobs:
  thehivedata:
  mispsqldata:

networks:
  SOC_NET:
    driver: bridge
